# STANDARD SCALER

In [9]:
import numpy as np

class StandardScaler():
    def __init__(self):
        self.params_ = {"mean":None, "std":None}

    def fit(self, X):
        self.params_["mean"] = np.mean(X, axis=0) #moyenne par colonne
        self.params_["std"] = np.std(X, axis=0)

    def transform(self, X):
        return (X - self.params_["mean"]) / self.params_["std"]

    def fit_transform(self, X):
        return self.fit(X).transform(X)

In [10]:
X = np.array([[77, 88, 99] , [31,42,63] , [11,22,33]])
scaler = StandardScaler()
scaler.fit(X)
scaler.transform(X)

array([[ 1.35106563,  1.35106563,  1.26012384],
       [-0.31364024, -0.31364024, -0.07412493],
       [-1.0374254 , -1.0374254 , -1.18599891]])

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit(X))
print(scaler.transform(X))

StandardScaler(copy=True, with_mean=True, with_std=True)
[[ 1.35106563  1.35106563  1.26012384]
 [-0.31364024 -0.31364024 -0.07412493]
 [-1.0374254  -1.0374254  -1.18599891]]
